import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Activity from './models/Activity.js';

dotenv.config();

const initialActivities = [
  {
    title: "تجربة الطبخ المغربي التقليدي",
    titleFr: "Cours de Cuisine Traditionnelle",
    titleEn: "Traditional Cooking Experience",
    description: "اكتشف أسرار المطبخ المغربي الأصيل مع طاهٍ محلي. تعلم تحضير الطاجين والكسكس وأطباق تقليدية أخرى باستخدام مكونات طازجة من السوق المحلي.",
    descriptionFr: "Découvrez les secrets de la cuisine marocaine authentique avec un chef local. Apprenez à préparer le tajine, le couscous et d'autres plats traditionnels.",
    descriptionEn: "Discover the secrets of authentic Moroccan cuisine with a local chef. Learn to prepare tagine, couscous and other traditional dishes.",
    category: "طبخ",
    price: 250,
    duration: "3 ساعات",
    durationFr: "3 heures",
    durationEn: "3 hours",
    hasGuide: true,
    image: "/images/activities/cooking.png",
    hostId: "host1",
    rating: 4.8,
    location: "تنغير، المدينة القديمة",
    locationFr: "Vieille ville, Tinghir",
    locationEn: "Old Town, Tinghir",
    lat: 31.5135,
    lng: -5.5295,
    difficulty: "سهل",
    color: "yellow",
  },
  {
    title: "مغامرة المشي في مضيق تودغا",
    titleFr: "Randonnée dans les Gorges du Todgha",
    titleEn: "Hiking Adventure in Todra Gorge",
    description: "استمتع بمشي رائع عبر مضيق تودغا الشهير. مسار يأخذك عبر جدران صخرية شاهقة يصل ارتفاعها إلى 300 متر.",
    descriptionFr: "Profitez d'une randonnée magnifique à travers les célèbres Gorges du Todgha avec des parois rocheuses de 300 mètres.",
    descriptionEn: "Enjoy a magnificent walk through the famous Todra Gorge. A trail that takes you through towering rock walls up to 300 meters high.",
    category: "مشي",
    price: 220,
    duration: "5 ساعات",
    durationFr: "5 heures",
    durationEn: "5 hours",
    hasGuide: true,
    image: "/images/activities/hiking.png",
    hostId: "host1",
    rating: 4.9,
    location: "مضيق تودغا، تنغير",
    locationFr: "Gorges du Todgha, Tinghir",
    locationEn: "Todra Gorge, Tinghir",
    lat: 31.5889,
    lng: -5.5703,
    difficulty: "متوسط",
    color: "green",
  },
  {
    title: "تسلق جبال الأطلس الكبير",
    titleFr: "Escalade dans le Haut Atlas",
    titleEn: "High Atlas Climbing",
    description: "تحدّ نفسك مع تجربة تسلق مثيرة في جبال الأطلس. مسارات متنوعة تناسب جميع المستويات مع معدات كاملة مخصصة.",
    descriptionFr: "Relevez le défi avec une expérience d'escalade passionnante dans les montagnes de l'Atlas pour tous les niveaux.",
    descriptionEn: "Challenge yourself with an exciting climbing experience in the Atlas Mountains with various levels.",
    category: "تسلق",
    price: 500,
    duration: "يوم كامل",
    durationFr: "Journée complète",
    durationEn: "Full day",
    hasGuide: true,
    image: "/images/activities/climbing.jpg",
    hostId: "host1",
    rating: 4.7,
    location: "جبال الأطلس، تنغير",
    locationFr: "Haut Atlas, Tinghir",
    locationEn: "High Atlas, Tinghir",
    lat: 31.5900,
    lng: -5.5710,
    difficulty: "صعب",
    color: "violet",
  },
  {
    title: "جولة بالدراجات على ضفاف الواحة",
    titleFr: "Tour à Vélo dans l'Oasis",
    titleEn: "Oasis Bicycle Tour",
    description: "اركب دراجتك واستكشف واحة تنغير الخضراء. مسار مسطح وسهل يمر عبر أشجار النخيل والحقول التقليدية.",
    descriptionFr: "Prenez votre vélo et explorez l'oasis verdoyante de Tinghir à travers les palmiers et les champs traditionnels.",
    descriptionEn: "Ride your bike and explore the green oasis of Tinghir. A flat and easy path through palm trees and traditional fields.",
    category: "دراجات",
    price: 180,
    duration: "4 ساعات",
    durationFr: "4 heures",
    durationEn: "4 hours",
    hasGuide: false,
    image: "/images/activities/vtt.png",
    hostId: "host1",
    rating: 4.6,
    location: "واحة تنغير",
    locationFr: "Oasis de Tinghir",
    locationEn: "Tinghir Oasis",
    lat: 31.5147,
    lng: -5.5328,
    difficulty: "سهل",
    color: "orange",
  },
  {
    title: "جولة بالدراجات الرباعية (Quad)",
    titleFr: "Excursion en Quad",
    titleEn: "Quad Biking Tour",
    description: "اكتشف الصحراء والمناطق الجبلية على متن دراجة رباعية. مسارات متعددة تأخذك عبر مناظر طبيعية خلابة.",
    descriptionFr: "Découvrez le désert et les zones montagneuses en quad avec des paysages à couper le souffle.",
    descriptionEn: "Discover the desert and mountain areas on a quad bike with multiple trails through stunning landscapes.",
    category: "كواد",
    price: 550,
    duration: "ساعتان",
    durationFr: "2 heures",
    durationEn: "2 hours",
    hasGuide: true,
    image: "/images/activities/quad.png",
    hostId: "host1",
    rating: 4.7,
    location: "ضواحي تنغير",
    locationFr: "Environs de Tinghir",
    locationEn: "Tinghir Suburbs",
    lat: 31.5200,
    lng: -5.5400,
    difficulty: "متوسط",
    color: "orange",
  },
  {
    title: "ركوب الخيل في الواحة",
    titleFr: "Équitation dans l'Oasis",
    titleEn: "Horse Riding in the Oasis",
    description: "استكشف واحة تنغير على ظهر حصان عربي أصيل. جولة هادئة وممتعة عبر مسارات النخيل والقرى التقليدية.",
    descriptionFr: "Explorez l'oasis de Tinghir sur un pur-sang arabe à travers les palmiers et les villages traditionnels.",
    descriptionEn: "Explore the Tinghir oasis on an authentic Arabian horse through palm paths and traditional villages.",
    category: "ركوب الخيل",
    price: 300,
    duration: "ساعتان",
    durationFr: "2 heures",
    durationEn: "2 hours",
    hasGuide: true,
    image: "/images/activities/horse.jpeg",
    hostId: "host1",
    rating: 4.6,
    location: "واحة تنغير",
    locationFr: "Oasis de Tinghir",
    locationEn: "Tinghir Oasis",
    lat: 31.5180,
    lng: -5.5350,
    difficulty: "سهل",
    color: "pink",
  },
  {
    title: "قافلة الجمال عبر الصحراء",
    titleFr: "Caravane de Chameaux",
    titleEn: "Camel Caravan Experience",
    description: "عش تجربة قافلة الجمال الأصيلة عبر الكثبان الرملية. رحلة تأخذك إلى عالم آخر مع مرشد بربري محلي.",
    descriptionFr: "Vivez l'expérience authentique d'une caravane de chameaux à travers les dunes avec un guide local.",
    descriptionEn: "Live the authentic camel caravan experience through the sand dunes with a local Berber guide.",
    category: "ركوب الجمال",
    price: 200,
    duration: "3 ساعات",
    durationFr: "3 heures",
    durationEn: "3 hours",
    hasGuide: true,
    image: "/images/activities/camel.jpg",
    hostId: "host1",
    rating: 4.8,
    location: "صحراء تنغير",
    locationFr: "Désert de Tinghir",
    locationEn: "Tinghir Desert",
    lat: 31.5000,
    lng: -5.4800,
    difficulty: "سهل",
    color: "orange",
  },
  {
    title: "ورشة الفخار التقليدي",
    titleFr: "Atelier de Poterie Traditionnelle",
    titleEn: "Traditional Pottery Workshop",
    description: "تعلم فن الفخار المغربي التقليدي مع حرفي محلي. اصنع قطعتك الخاصة باستخدام تقنيات موروثة عبر الأجيال.",
    descriptionFr: "Apprenez l'art de la poterie marocaine avec un artisan local et créez votre propre pièce.",
    descriptionEn: "Learn the art of traditional Moroccan pottery with a local artisan using ancestral techniques.",
    category: "فخار",
    price: 150,
    duration: "ساعتان",
    durationFr: "2 heures",
    durationEn: "2 hours",
    hasGuide: true,
    image: "/images/activities/pottery.jpg",
    hostId: "host1",
    rating: 4.5,
    location: "تنغير، حي الحرفيين",
    locationFr: "Quartier des Artisans, Tinghir",
    locationEn: "Artisans Quarter, Tinghir",
    lat: 31.5110,
    lng: -5.5340,
    difficulty: "سهل",
    color: "pink",
  },
  {
    title: "ورشة النسيج الأمازيغي",
    titleFr: "Atelier de Tissage Amazigh",
    titleEn: "Amazigh Weaving Workshop",
    description: "اكتشف فن النسيج التقليدي الأمازيغي مع نساء التعاونية. تعلم كيف تُنسج الزرابي الملونة بأيدي ماهرة.",
    descriptionFr: "Découvrez l'art du tissage traditionnel amazigh avec les femmes de la coopérative.",
    descriptionEn: "Discover the traditional Amazigh weaving art with the women of the cooperative.",
    category: "نسيج",
    price: 150,
    duration: "3 ساعات",
    durationFr: "3 heures",
    durationEn: "3 hours",
    hasGuide: true,
    image: "/images/activities/weaving.jpg",
    hostId: "host1",
    rating: 4.7,
    location: "تعاونية النسيج، تنغير",
    locationFr: "Coopérative de Tissage, Tinghir",
    locationEn: "Weaving Cooperative, Tinghir",
    lat: 31.5120,
    lng: -5.5310,
    difficulty: "سهل",
    color: "purple",
  },
];

const restoreActivities = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/experiencia';
    await mongoose.connect(mongoUri);
    console.log("Connected to MongoDB. Restoring activities with new single-image schema...");

    try {
      await mongoose.connection.collection('activities').drop();
      console.log("Cleared existing activities.");
    } catch (e) {
      console.log("No existing activities collection to drop.");
    }

    await Activity.insertMany(initialActivities);
    console.log(`Successfully restored all ${initialActivities.length} activities with localized metadata!`);
    
    process.exit(0);
  } catch (error) {
    console.error("Error restoring activities:", error);
    process.exit(1);
  }
};

restoreActivities();
